#pragma once

const int WRONG_NUMBER_OF_ITEMS = -1;
const int WRONG_MAX_WEIGHT = -2;
const int DIFFERENT_VECTOR_SIZE_THEN_EXPECTED = -3;
const int NEGATIVE_POPULATION_SIZE = -4;
const int ODD_POPULATION_SIZE = -5;
const int WRONG_CROSSOVER_RATE = -6;
const int WRONG_MUTATION_RATE = -7;
const int NEGATIVE_NUMBER_OF_GENERATIONS = -8;
const int FILE_NOT_OPEN = -9;
const int NOT_ENOUGHT_ITEMS_IN_FILE = -10;
const int NEGATIVE_WEIGHT_OF_ITEM = -11;
const int NEGATIVE_VALUE_OF_ITEM = -12;
const int INVALID_TYPE_IN_FILE = -13;
const int SUCCESS = 0;

